version: 2.1

executors:
  working_directory: /root/saml_idp_metadata
  ruby_3_4:
    docker:
      - image: rubylang/ruby:3.4-dev-focal
  ruby_3_3:
    docker:
      - image: rubylang/ruby:3.3-dev-focal
  ruby_3_2:
    docker:
      - image: rubylang/ruby:3.2-dev-focal
  ruby_3_1:
    docker:
      - image: rubylang/ruby:3.1-dev-focal

commands:
  install_system_dependencies:
    description: "Install system dependencies"
    steps:
      - run:
          name: Install System Dependencies
          # https://circleci.com/docs/2.0/custom-images/#required-tools-for-primary-containers
          command: apt-get update -y && apt-get install -y ssh

  bundle_gems:
    description: "Bundle gems"
    steps:
      - run:
          name: Bundle gems
          command: |
            gem install bundler -v 2.4.20 --no-document --force
            bundle install

  run_tests:
    description: "Run tests"
    steps:
      - run:
          name: Run tests
          command: |
            bundle exec rake
            bundle exec rubocop
      - store_artifacts:
          path: coverage

jobs:
  run_tests_on_ruby_3_4:
    executor: ruby_3_4
    steps:
      - install_system_dependencies
      - checkout
      - bundle_gems
      - run_tests
  run_tests_on_ruby_3_3:
    executor: ruby_3_3
    steps:
      - install_system_dependencies
      - checkout
      - bundle_gems
      - run_tests
  run_tests_on_ruby_3_2:
    executor: ruby_3_2
    steps:
      - install_system_dependencies
      - checkout
      - bundle_gems
      - run_tests

  run_tests_on_ruby_3_1:
    executor: ruby_3_1
    steps:
      - install_system_dependencies
      - checkout
      - bundle_gems
      - run_tests

workflows:
  version: 2
  test:
    jobs:
      - run_tests_on_ruby_3_4
      - run_tests_on_ruby_3_3
      - run_tests_on_ruby_3_2
      - run_tests_on_ruby_3_1
