version: 2.1

executors:
  ruby:
    parameters:
      version:
        type: string
    docker:
      - image: rubylang/ruby:<< parameters.version >>-dev-focal
    working_directory: /root/saml_idp_metadata

commands:
  install_system_dependencies:
    description: "Install system dependencies"
    steps:
      - run:
          name: Install System Dependencies
          # https://circleci.com/docs/2.0/custom-images/#required-tools-for-primary-containers
          command: apt-get update -y && apt-get install -y ssh

  bundle_gems:
    description: "Bundle gems"
    steps:
      - run:
          name: Bundle gems
          command: |
            gem install bundler -v 2.5.22 --no-document --force
            bundle install

  run_tests:
    description: "Run tests"
    steps:
      - run:
          name: Run tests
          command: |
            bundle exec rake
            bundle exec rubocop
      - store_artifacts:
          path: coverage

jobs:
  test:
    parameters:
      ruby-version:
        type: string
    executor:
      name: ruby
      version: << parameters.ruby-version >>
    steps:
      - install_system_dependencies
      - checkout
      - bundle_gems
      - run_tests

workflows:
  version: 2
  test:
    jobs:
      - test:
          matrix:
            parameters:
              ruby-version:
                - "3.2"
                - "3.3"
                - "3.4"
