name: Ruby

on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        ruby: [ '2.5.x', '2.6.x', '2.7.x' ]
    name: Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@master
      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          architecture: 'x64'
      - name: Build and test
        run: |
          gem install bundler -v 2.1.2
          bundle install
          bundle exec rubocop
          bundle exec rake
