name: Ruby Tests

on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    name: Ruby ${{ matrix.ruby-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - '3.2'
          - '3.3'
          - '3.4'
    container:
      image: rubylang/ruby:${{ matrix.ruby-version }}-dev-focal

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup bundler
        run: gem install bundler -v 2.5.22 --force --no-document

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Run linting
        run: bundle exec rubocop

      - name: Run tests
        run: bundle exec rake

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-${{ matrix.ruby-version }}
          path: coverage/
